### ISSUE TITLE
Get-Content : Cannot find path

### ISSUE THREAD

**Issue by Manakanapa** [lord-carlos/nvidia-update#22]
Getting a strange issue after a few months of use.

Update file downloads successfully to temp folder and then...

Get-Content : Cannot find path 'C:\Users\username\AppData\Local\Temp\NVIDIA\436.48.exe\setup.cfg' because it does not exist.
At C:\Users\username\Documents\WindowsPowerShell\Modules\NvidiaUpdate\NvidiaUpdate.psm1:96 char:6
+     (Get-Content "$extractFolder\setup.cfg") | Where-Object {$_ -notm ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\username...36.48\setup.cfg:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by lord-carlos** [comment]
Is there anything in `C:\Users\username\AppData\Local\Temp\NVIDIA`?
Do you have the latest version of the script?

**Comment by Manakanapa** [comment]
I'll try updating and run it again.

It downloads the file successfully to ../temp/Nvidia/xxx.exe but then cannot open.

**Comment by lord-carlos** [comment]
Can you open it by "hand"?

**Comment by Manakanapa** [comment]
Yes, I had a rummage around in the exe. Everything looks fine...

**Comment by lord-carlos** [comment]
Not sure where to go from here :/
Maybe it's a permission issue? Tried deleting `C:\Users\username\AppData\Local\Temp\NVIDIA` ?

**Comment by Manakanapa** [comment]
Hi, Yes. Everything seems to be working now...

**Comment by lord-carlos** [comment]
Weird. 🤷‍♀️
