### ISSUE TITLE
Version Detection Changed with 471.11

### ISSUE THREAD

**Issue by OmbertoOreily** [lord-carlos/nvidia-update#34]
With the release of driver version 30.0.14.7111, the script is detecting it as ".11.1".  I noticed if you changed the .DriverVersion.Substring(7) to .DriverVersion.Substring(6) it will detect correctly, but then older cards with earlier drivers then do not report correctly.

**Comment by alex4rks** [comment]
fix:
`$ins_version = ((Get-WmiObject Win32_PnPSignedDriver | 
        Where-Object { $_.devicename -like "*nvidia*" -and $_.devicename -notlike "*audio*" -and $_.devicename -notlike "*USB*" -and $_.devicename -notlike "*SHIELD*" }).DriverVersion.Replace('.', '')[-5..-1] -join '').insert(3, '.')`

**Comment by alex4rks** [comment]
or version can be found like this:
```
$VideoController = Get-WmiObject -ClassName Win32_VideoController | Where-Object { $_.Name -match "NVIDIA" }
$ins_version = ($VideoController.DriverVersion.Replace('.', '')[-5..-1] -join '').insert(3, '.')
```

**Comment by OmbertoOreily** [comment]
Thanks Alex,

That does the trick, much appreciated!

**Comment by lord-carlos** [comment]
Can some one create a pull request? Would be nice.

**Comment by OmbertoOreily** [comment]
Forgive me Lord Carlos,

For I am new at GitHub.  Is a Pull Request the preferred way of reporting a bug?  I want to be a good citizen here, I am very thankful for your PS script for Nvidia!

All best…

Jason

Jason Lang
Senior Consultant
AP3Dconsulting
900 Broadway, Suite 802
New York, NY 10003
t: (212) 633-9403 (x111)
e: ***@***.******@***.***>

**Comment by lord-carlos** [comment]
> Forgive me Lord Carlos, For I am new at GitHub. Is a Pull Request the preferred way of reporting a bug?

You did fine :) Everybody did fine
Here is the correct way of reporting the bug.
A pull request is a good idea if someone has a working change for the code. That way I can accept and merge the new code with the press of a button.

I can also take the code @alex4rks wrote and put it in my self. But it will take a few days and he will not get "the credit" as it would look like i write it.

**Comment by OmbertoOreily** [comment]
Thanks Carlos,

I was just reading up on the pull requests on GitHub’s site.  I think I got the idea a bit better.

Thanks again for all your work!

All best…

Jason

Jason Lang
Senior Consultant
AP3Dconsulting
900 Broadway, Suite 802
New York, NY 10003
t: (212) 633-9403 (x111)
e: ***@***.******@***.***>

**Comment by alex4rks** [comment]
@lord-carlos, you can check here: https://github.com/lord-carlos/nvidia-update/pull/35

**Comment by lord-carlos** [comment]
Pullrequest #35 merged.
I will test it in a few days and close this bug.
