### ISSUE TITLE
PSA: Nvidia no longer releasing standard drivers

### ISSUE THREAD

**Issue by ghost** [lord-carlos/nvidia-update#38]
Starting with version 496.13 (October 12, 2021) the only download option is DCH. This can be verified with switching the toggle on the advanced driver search from "Standard" to "DCH".

As it currently stands, I'm sad to say that this tool no longer provides the same value in its current iteration. The URL used to download the drivers can be easily fixed, but am unsure at this time if DCH drivers can be extracted and manipulated in the same manner as Standard drivers.

Will do some testing and report back.

**Comment by ghost** [comment]
DCH drivers can be extracted and manipulated just like Standard drivers.

**Comment by OmbertoOreily** [comment]
Hello @iorv3th, I was testing moving over to DCH drivers as well and modified the detection URL to be:

`https://www.nvidia.com/Download/processFind.aspx?psid=101&pfid=816&osid=57&lid=1&whql=1&lang=en-us&ctk=0&dtcid=1`

But when running I am getting an error that the link does not exist on the server (Start-BitsTransfer : HTTP status 404: The requested URL does not exist on the server.)

Would you mind sharing what you got to work when switching over to updating DCH drivers?

Thanks!

**Comment by ghost** [comment]
@OmbertoOreily This is the url I use:
https://international.download.nvidia.com/Windows/$version/$version-desktop-$windowsVersion-$windowsArchitecture-international-dch-whql.exe

This is on line 127 for me, should be the same for you.

**Comment by OmbertoOreily** [comment]
@iorv3th That worked for me too.  Thank you sir!

**Comment by lord-carlos** [comment]
Thanks for the help. Testing it now.
When I tried to switch from standart to DCH it got a couple of errors while installing. 
![image](https://user-images.githubusercontent.com/155855/159337882-edacba2d-88b1-4489-8c2a-8f884dded10e.png)
But it still seems to work.

Will do some testing and push the updates soon.
Next time just make a pull request and I can merge it faster. Thank you :)

**Comment by ghost** [comment]
Thanks Carl.

Apologies for not putting up a PR. I don't have a development environment set up and am not really a used to working with GitHub as I'm not a developer.

**Comment by lord-carlos** [comment]
> Apologies for not putting up a PR. I don't have a development environment set up and am not really a used to working with GitHub as I'm not a developer.

No problem.

It seems to have installed just fine. But I have not looked at the file structure if out extraction and removing of privacy stuff still works 🤷‍♀️

Let me know if stuff explodes.
