### ISSUE TITLE
Line 136 deletes the ENTIRE directory

### ISSUE THREAD

**Issue by SkilledAlpaca** [lord-carlos/nvidia-update#9]
When I added this line in testing, I didn't full grasp what it did. This also deletes the root folder and should be removed or commented out until I find a fix. 

https://github.com/lord-carlos/nvidia-update/blob/e58981c314d31f00cd48cfa12b72b6414624b827/nvidia.ps1#L136

**Comment by teoxoy** [comment]
Just tested it and it works fine for me.

**Comment by lord-carlos** [comment]
Fixed with pullrequest #14
